version: '3.1'

services:

    rabbit:
        image: rabbitmq:3-management
        hostname: rabbitMq
        ports:
            - "15672:15672"
            - "5672:5672"
        labels:
            NAME: "rabbitmq"
        restart: always
        environment: 
            RABBITMQ_DEFAULT_USER: "rabbitMq"
            RABBITMQ_DEFAULT_PASS: "rabbitMq"
            RABBITMQ_DEFAULT_VHOST: "/"
        networks:
            testing_net:
                ipv4_address: 172.20.0.4

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16